### ISSUE TITLE
cannot update user properties

### ISSUE THREAD

**Issue by omar11hassan** [klaviyo/klaviyo-react-native-sdk#130]
### Checklist

- [X] I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-react-native-sdk/blob/master/.github/CONTRIBUTING.md)
- [x] I have determined whether this bug is also reproducible in a vanilla project, such as the example app in this repository.
- [x] If possible, I've reproduced the issue using the `master` branch or latest release of this package.
- [X] This issue hasn't been addressed in an [existing issue](https://github.com/klaviyo/klaviyo-react-native-sdk/issues) or [pull request](https://github.com/klaviyo/klaviyo-react-native-sdk/pulls)

### Description

```markdown
here is how i try to update the user
`Klaviyo.setProfileAttribute('score', '22');`
```

### Expected behavior

```markdown
property score should be added/updated in user profile.
```

### Actual behavior

```markdown
profile update time is updated, however no properties is being added or updated
```

### Steps to reproduce

```markdown
1 - set user profile
 2 - update user attributes
```

### The Klaviyo React Native SDK version information

0.2.0

### Environment Description

 OS: macOS 12.7.1
  CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Memory: 108.12 MB / 16.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 16.20.2
    path: ~/.nvm/versions/node/v16.20.2/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 8.19.4
    path: ~/.nvm/versions/node/v16.20.2/bin/npm
  Watchman:
    version: 2023.11.27.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9014738
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /usr/local/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

**Comment by ajaysubra** [comment]
@omar11hassan thanks for reporting this. We are looking into it. In the meantime can you please confirm if you are doing this test on iOS/android?

**Comment by omar11hassan** [comment]
> @omar11hassan thanks for reporting this. We are looking into it. In the meantime can you please confirm if you are doing this test on iOS/android?

iOS

**Comment by ajaysubra** [comment]
Hi @omar11hassan we are actively working on this. Will keep you posted when we have a fix. Thanks for your patience.

**Comment by ajaysubra** [comment]
Hey @omar11hassan we have fixed the issue you reported and created a new release [0.3.0](https://github.com/klaviyo/klaviyo-react-native-sdk/releases/tag/0.3.0). Please update to this release and you should be all set. Please let us know if you have any other issues. Thanks!
