### ISSUE TITLE
Rich Push iOS issue : 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by youcefswoo** [klaviyo/klaviyo-react-native-sdk#141]
### Checklist

- [X] I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-react-native-sdk/blob/master/.github/CONTRIBUTING.md)
- [ ] I have determined whether this bug is also reproducible in a vanilla project, such as the example app in this repository.
- [X] If possible, I've reproduced the issue using the `master` branch or latest release of this package.
- [X] This issue hasn't been addressed in an [existing issue](https://github.com/klaviyo/klaviyo-react-native-sdk/issues) or [pull request](https://github.com/klaviyo/klaviyo-react-native-sdk/pulls)

### Description

```markdown
I was attempting to integrate rich notifications. I followed the instructions step by step in the iOS documentation. I created the Notification Service Extension as mentioned. However, when I downloaded the KlaviyoSwiftExtension using CocoaPods, I encountered the error and couldn't build the project.
```

### Expected behavior

```markdown
I expected the build to be successful.
```

### Actual behavior

```markdown
Build error :'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.
```

### Steps to reproduce

```markdown
Follow the steps to integrate Rich Push.
```

### The Klaviyo React Native SDK version information

0.3.1

### Environment Description

react native 0.73.3

**Comment by ajaysubra** [comment]
@youcefswoo could you please share your podfile?

**Comment by youcefswoo** [comment]
> @youcefswoo could you please share your podfile?
@ajaysubra this my Podfile.
<img width="573" alt="image" src="https://github.com/klaviyo/klaviyo-react-native-sdk/assets/152196925/07ffe625-1232-4331-80d0-300ee3a7a90b">

i m using [firebase](https://rnfirebase.io/) and [react-native-permissions](https://github.com/zoontek/react-native-permissions). and for the name of the extension is `RichNotification`

**Comment by youcefswoo** [comment]
@ajaysubra 
And this is the error that I encounter in the `KlaviyoEnvironment` struct when attempting to build the project.
<img width="899" alt="image" src="https://github.com/klaviyo/klaviyo-react-native-sdk/assets/152196925/be209d46-cc42-4234-9c1e-17fc36a09d84">

**Comment by youcefswoo** [comment]
@ajaysubra After updating the podfile to 

<img width="681" alt="image" src="https://github.com/klaviyo/klaviyo-react-native-sdk/assets/152196925/1f1a0904-3f3e-43c8-9c06-5949b01eddb6">

i got this new build error

Cycle inside APP_NAME; building could produce unreliable results.

**Comment by ajaysubra** [comment]
> @ajaysubra After updating the podfile to
> 
> <img alt="image" width="681" src="https://private-user-images.githubusercontent.com/152196925/319659088-1f1a0904-3f3e-43c8-9c06-5949b01eddb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Nzk3MDUsIm5iZiI6MTcxMjY3OTQwNSwicGF0aCI6Ii8xNTIxOTY5MjUvMzE5NjU5MDg4LTFmMWEwOTA0LTNmM2UtNDNjOC05YzA2LTU5NDliMDFlZGRiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxNjE2NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDU0MzU3NzViNmIyYzRmMzNlMGJlNWE0YzU4MGNkN2QwYzg3OTIyOTBlZTEyNzFiOGU5M2Y5ODVlNDRmZWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1VIRuCQOy9ZhfFYELaKpB9Jhix4Uj_SZ_B9Feq7DIn4">
> i got this new build error
> 
> Cycle inside APP_NAME; building could produce unreliable results.

@youcefswoo I created a PR here in the example app that uses `KlaviyoSwiftExtension` in the podfile. I tested this locally and it seems to work. I have not seen that build error on my end when trying to use extension pod.

**Comment by youcefswoo** [comment]
@ajaysubra After reviewing the example and following it step by step, I had the same build issue [here](https://github.com/klaviyo/klaviyo-react-native-sdk/issues/141#issuecomment-2037538391). I resolved the issue with this [suggestion](https://github.com/OneSignal/react-native-onesignal/issues/1569#issuecomment-1817866408)  Thanks for your support.

**Comment by ajaysubra** [comment]
@youcefswoo Thanks for posting your solution here. Closing this issue now. Feel free to reach out if you need anything else.

**Comment by youcefswoo** [comment]
@ajaysubra  thanks
