### ISSUE TITLE
Integrating the tracking of open events on the Android side of the example.

### ISSUE THREAD

**Issue by youcefswoo** [klaviyo/klaviyo-react-native-sdk#144]
### Checklist

- [X] I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-react-native-sdk/blob/master/.github/CONTRIBUTING.md)
- [X] This issue hasn't been addressed in an [existing issue](https://github.com/klaviyo/klaviyo-react-native-sdk/issues) or [pull request](https://github.com/klaviyo/klaviyo-react-native-sdk/pulls)

### Description

```markdown
The documentation for integrating the tracking of open events is not clear, as native Kotlin projects and React Native have different architectures.
```

### Proposed Solution

```markdown
I'm writing to ask for further explanation in the documentation, along with a demonstration on the Android side of the example.
```

**Comment by evan-masseau** [comment]
Hi, the short answer is that on both platforms we require you to write native code to handle push opens because notification opens are handled very differently by platform. That is why we link to our native SDKs' documentation. 
For Android that will mean handling an intent from the main activity. I will work on an example app update for the android side to demonstrate, but wanted to answer you sooner than later.

**Comment by evan-masseau** [comment]
Hmm which version of the RN SDK? And I bet you're initializing from typescript code?

**Comment by evan-masseau** [comment]
Can you see error output in logcat? This is probably a timing issue of invoking Klaviyo prior to initializing, going to have to think about how we can work around that.

**Comment by youcefswoo** [comment]
@evan-masseau yes, I'm initializing the SDK on the React Native side. Do you still need the logs?

**Comment by evan-masseau** [comment]
@youcefswoo I can probably get started with this much detail. Thank you for all your contributions, I'll update as soon as I can!

**Comment by evan-masseau** [comment]
> @evan-masseau I switched the initialization of the SDK on the native side to make the tap on notifications work. So, it's not a bug, but I believe it would be beneficial for the SDK to offer a way to perform tracking on the React Native side as well.

Fully agree, my first goal will be to enable the open tracking on Android without requiring you to also move your initialization logic. Tracking opens for both platforms from react native code is a harder lift, so I'm going to consider that a separate goal.

**Comment by evan-masseau** [comment]
With our latest release, `0.4.2`, the timing issue related to tracking an opened push event and initializing Klaviyo SDK from react native code should now be resolved. We now hold that event in memory until Klaviyo gets initialized to work around this platform/timing limitation. Thanks for bearing with us, we'll continue to consider options for tracking this event from react native code, however as I mentioned before doing that in a cross-platform way is going to be tricky.

**Comment by oorestisime** [comment]
> > @evan-masseau I switched the initialization of the SDK on the native side to make the tap on notifications work. So, it's not a bug, but I believe it would be beneficial for the SDK to offer a way to perform tracking on the React Native side as well.
> 
> Fully agree, my first goal will be to enable the open tracking on Android without requiring you to also move your initialization logic. Tracking opens for both platforms from react native code is a harder lift, so I'm going to consider that a separate goal.

hi @evan-masseau , any news regarding offering open tracking capabilities on RN? I am currently working on an expo app and doing this from a managed expo isnt the most trivial i would say.

**Comment by SiluntKnight** [comment]
Hi @evan-masseau is there any further update on this? this would be great if we could get access to this within RN
