### ISSUE TITLE
Expo plugin for integrating native code for tracking open push

### ISSUE THREAD

**Issue by oorestisime** [klaviyo/klaviyo-react-native-sdk#164]
### Checklist

- [X] I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-react-native-sdk/blob/master/.github/CONTRIBUTING.md)
- [X] This issue hasn't been addressed in an [existing issue](https://github.com/klaviyo/klaviyo-react-native-sdk/issues) or [pull request](https://github.com/klaviyo/klaviyo-react-native-sdk/pulls)

### Description

```markdown
The descriptions on how to add native code for tracking Open Push notifications seems rather straightforward for any project that is native or is ejected.
```

### Proposed Solution

```markdown
It would be nice to have an expo plugin that does the solutions for both android and ios and the only thing users need to do is just installed the package.
```

**Comment by ndurell** [comment]
Hey Orestis,
Thanks for filing this issue! At this time we do not have specific plans to support expo but we are considering future support. For now you will likely need to add native code as indicated in the setup docs to enable Klaviyo push notifications.

Thanks,
Noah
