### ISSUE TITLE
Add multiple klaviyo account to project

### ISSUE THREAD

**Issue by thanhxuan071003** [klaviyo/klaviyo-react-native-sdk#165]
### Checklist

- [X] I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-react-native-sdk/blob/master/.github/CONTRIBUTING.md)
- [X] This issue hasn't been addressed in an [existing issue](https://github.com/klaviyo/klaviyo-react-native-sdk/issues) or [pull request](https://github.com/klaviyo/klaviyo-react-native-sdk/pulls)

### Description

```markdown
Hello,

I have a problem with Klaviyo. I have multiple Klaviyo accounts, and I want to add all these accounts to one React Native project. Depending on each event, I will send to a different account. Is there any way to do this?

Thank you.
```

### Proposed Solution

```markdown
I can't find any documentation that addresses this. Does Klaviyo support adding multiple accounts to React Native? If it is supported, please provide the documentation. Thanks
```

**Comment by ndurell** [comment]
Thanks for reaching out. I'm trying to understand your use-case a little better.

1. Are you trying to have multiple companies initialized at the same time and send events to any of the initialized companies?
or
2. Are you trying to have any one company initialized at any given time and allow switching of companies within your app?

If it's 2, it is possible on the app, but it's not something we officially support or have documents for unfortunately at this point. However, feel free to let us know a little more about your use-case and we can take it as a feature request on our end.
