### ISSUE TITLE
Push Notification open event tracking iOS 

### ISSUE THREAD

**Issue by SiluntKnight** [klaviyo/klaviyo-react-native-sdk#181]
### Checklist

- [X] I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-react-native-sdk/blob/master/.github/CONTRIBUTING.md)
- [X] This issue hasn't been addressed in an [existing issue](https://github.com/klaviyo/klaviyo-react-native-sdk/issues) or [pull request](https://github.com/klaviyo/klaviyo-react-native-sdk/pulls)

### Description

```markdown
I am trying to track open events for push notifications on our React Native app, I have followed the instructions for Android and that appears to work fine, however for iOS all our native code is written in Objective-C and I believe this to be the case for all RN apps. I can't see a clear example of how we can track these events as the native code for the Klaviyo SDK on iOS is written in Swift. I am missing something here?
```

### Proposed Solution

```markdown
Provide examples of how you can track events natively through React Native and iOS as suggested is the case in the docs instead of referring to a solely native Swift approach.
```

**Comment by ndurell** [comment]
Hey There,
Sorry for the late response and for the lack of clear documentation on this.
We have an example app in this repo. If you don't mind bridging your objective-c code over to our swift you can use this [class](https://github.com/klaviyo/klaviyo-react-native-sdk/blob/master/example/ios/KlaviyoReactNativeSdkExample/PushNotificationsHelper.swift) in our example app. For handling an open push event look at the function `handleReceivingPush`.
Let me know if this helps or if you need more info.

Thanks,
Noah

**Comment by SiluntKnight** [comment]
Hi @ndurell thanks for getting back to me, I'm totally new to this - I'll take a look at bridging, thanks for the example that should get me on my way!

**Comment by AhmadNaeemK** [comment]
@ndurell Is there any way to track the `Opened Push` event with [React Native Notifications](https://www.npmjs.com/package/react-native-notifications). It monitors the notifications and does not trigger `didReceiveNotification` we wrote in AppDelegate.
