### ISSUE TITLE
Cannot run pod install [Add XCode 12.4 Support]

### ISSUE THREAD

**Issue by h-dung-95** [klaviyo/klaviyo-react-native-sdk#59]
### Description

```markdown
I'm install yarn add klaviyo-react-native-sdk
cd ios run pod install
```

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla project
- [ ] If possible, I've reproduced the issue using the `master` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/klaviyo/klaviyo-react-native-sdk/issues) or [pull request](https://github.com/klaviyo/klaviyo-react-native-sdk/pulls).

**Comment by h-dung-95** [comment]
![Screenshot 2024-01-26 at 09 27 53](https://github.com/klaviyo/klaviyo-react-native-sdk/assets/113409857/888951f0-8e7f-4739-874c-813ef0b1f8f7)

**Comment by evan-masseau** [comment]
Would you mind sharing your iOS minimum deployment target?

**Comment by h-dung-95** [comment]
i'm use react-native: 0.72.0

**Comment by h-dung-95** [comment]
`
Would you mind sharing your iOS minimum deployment target?

`
What do you mean?

**Comment by evan-masseau** [comment]
Thanks for your feedback. At this time, the Klaviyo Swift SDK has a minimum deployment target of 13. I see that the version of React Native that you are using has a default minimum deployment target of 12.4.
We are going to investigate options on our end. In the mean time to get you unblocked at least for development purposes, you could try changing your minimum deployment target to 13. Where you make that change may depend on your project, typically it'd be in your podfile looking something like this

```
platform :ios, min_ios_version_supported
```

This [thread](https://github.com/stripe/stripe-react-native/issues/1280#issuecomment-1828346834) has some relevant discussion how to update it. You could simply change `min_ios_version_supported` to 13.0, or you could use a snippet like this, and set the version from the XCode UI. 

```
#######
# Read min iOS version from Xcode project and set as min iOS version for Podfile
require 'xcodeproj'

project_path = './KlaviyoRNTestApp.xcodeproj'
project = Xcodeproj::Project.open(project_path)
min_ios_version_supported = project.build_configurations.first.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
######

platform :ios, min_ios_version_supported
```

Stay tuned, we will follow up on this thread as we investigate further

**Comment by evan-masseau** [comment]
FYI We've updated the readme to be clearer about platform requirements. Supporting 12.4 may be a longer term project, so for now updating `min_ios_version_supported` to 13 is our recommended fix.
