### ISSUE TITLE
setPushToken from react-native layer

### ISSUE THREAD

**Issue by appdeveloperdd** [klaviyo/klaviyo-react-native-sdk#65]
### Description

```markdown
Set Push token feature is missing.
```

### Proposed Solution

```markdown
In the Set Push token feature we need to Send Firebase push token to Klaviyo.

In Native code we can achive using below methods:

Android: Klaviyo.setPushToken("PUSH_TOKEN")
iOS: KlaviyoSDK().set(pushToken: "PUSH_TOKEN")
```

**Comment by appdeveloperdd** [comment]
You can create one method like setPushToken. Inside this token you can send push token like below example.

 try {
    const token = await messaging().getToken();
    console.log({ token });
    Klaviyo.setPushToken(token);
  } catch (e) {
    console.log(e);
  }

We can use @react-native-firebase/messaging package for push notification token and pass it to the setPushToken. Also you can create a setPushToken method in Android and iOS and implement Native Klaviyo implementation.

**Comment by evan-masseau** [comment]
We will investigate this, but perhaps you will know the answer: are you able to retrieve the APNs push token from react native code? 
Klaviyo does not support sending to Apple devices via Firebase Cloud Messaging, only APNs. From what I can tell, the code snippet you posted would result in sending an FCM token to Klaviyo for your iOS devices. Avoiding that confusion is one major reason that we opted to direct people to call `setPushToken` from the native layer at this time.

**Comment by appdeveloperdd** [comment]
We can use below snippet to Send Android Firebase push token and iOS APNs push token in React Native.

try {
    let token = '';
    if (Platform.OS === 'android') {
       **token = await messaging().getToken();**
    } else {
      const authorizationStatus = await messaging().requestPermission();
      if (authorizationStatus === messaging.AuthorizationStatus.AUTHORIZED) {
        **token = await messaging().getAPNSToken();**
      }
    }
 **Klaviyo.setPushToken(token);**

  } catch (e) {
    console.log(e);
  }

Is this correct way I'm doing?

**Comment by evan-masseau** [comment]
Thanks so much, yes that `messaging().getAPNSToken()` seems like the critical piece I wasn't sure of.

**Comment by evan-masseau** [comment]
Sorry, did not intend to close.

**Comment by ajaysubra** [comment]
@appdeveloperdd @evan-masseau has been hard to work bridging `setToken` over to react native and we should have a release with version `0.2.0` soon. Please keep an eye out. Thanks for your feedback!

**Comment by evan-masseau** [comment]
Hi folks, our first release supporting initialize and setPushToken from react native has just gone out: [v0.2.0](https://github.com/klaviyo/klaviyo-react-native-sdk/releases/tag/0.2.0)
