### ISSUE TITLE
Add a method to provide API key from from react-native context

### ISSUE THREAD

**Issue by UncleClapton** [klaviyo/klaviyo-react-native-sdk#69]
### Description

```markdown
Our Public API Key cannot be determined until after specific initialization steps are performed in our JavaScript code, however the current implementation requires us to provide the key to the native libraries before that initialization can occur.
```

### Proposed Solution

```markdown
Introduce a bridge function to either:
* initialize the native libraries from JS, or
* a way to re-initialize with the final determined key after we've finished our setup in react-native code.
```

### Additional Context

```markdown
Our app is a multi-region application, and we hold separate Klaviyo instances for each major region.

Our exact limitation here is that the user's region is determined by complex logic which exists in our JS Code, and is not available to the native side during the app's initialization.
```

**Comment by ajaysubra** [comment]
Hey @UncleClapton - Thanks for reaching out with your request. We are looking into this on our end and will report back when we have an update.

**Comment by ajaysubra** [comment]
@UncleClapton quick update here - we have some limitations on android that prevents us from immediately bridging initialize method to react native. Having said that, we are exploring ways to navigate this limitation and eventually bridge that method. This is going to take some time as we work through this and we'll keep you updated via this issue. Thanks!

**Comment by UncleClapton** [comment]
Awesome to hear. Thank you to all involved! 🎉

**Comment by evan-masseau** [comment]
Hi folks, our first release supporting initialize and setPushToken from react native has just gone out: [v0.2.0](https://github.com/klaviyo/klaviyo-react-native-sdk/releases/tag/0.2.0)
